# Convert the four approved 300x300 JPEG portraits into firmware flash data.
# Usage: ruby scripts/embed_robot_home_art.rb assets/robot-home include/RobotHomeArtData.h

abort 'expected ASSET_DIRECTORY OUTPUT.h' unless ARGV.size == 2

asset_directory, output_path = ARGV
assets = {
  'Bumblebee' => 'bumblebee.jpg',
  'Optimus' => 'optimus.jpg',
  'Megatron' => 'megatron.jpg',
  'Starscream' => 'starscream.jpg'
}

text = <<~HEADER
  // SPDX-License-Identifier: MIT
  // Generated by scripts/embed_robot_home_art.rb. Do not edit by hand.
  #pragma once
  #include <cstddef>
  #include <cstdint>
  #if defined(ARDUINO)
  #include <pgmspace.h>
  #define ROBOT_HOME_ART_PROGMEM PROGMEM
  #else
  #define ROBOT_HOME_ART_PROGMEM
  #endif
  namespace robot_home::art_data {
HEADER

assets.each do |name, filename|
  bytes = File.binread(File.join(asset_directory, filename)).bytes
  abort "#{filename} is not a JPEG" unless bytes.first(2) == [0xff, 0xd8] && bytes.last(2) == [0xff, 0xd9]
  abort "#{filename} exceeds 50 KiB" unless bytes.size < 50 * 1024
  text += "inline const std::uint8_t k#{name}Jpg[] ROBOT_HOME_ART_PROGMEM = {\n"
  bytes.each_slice(16) do |row|
    text += '  ' + row.map { |byte| format('0x%02x', byte) }.join(', ') + ",\n"
  end
  text += "};\n"
  text += "inline constexpr std::size_t k#{name}JpgSize = sizeof(k#{name}Jpg);\n"
end

text += <<~FOOTER
  }  // namespace robot_home::art_data
  #undef ROBOT_HOME_ART_PROGMEM
FOOTER

File.write(output_path, text)
